// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXIz5IvaBTZR_pt0n6Z9WF1TzvquleYDo',
    appId: '1:423063738443:web:33646b15473f7c5fe995ce',
    messagingSenderId: '423063738443',
    projectId: 'chat-app-a169a',
    authDomain: 'chat-app-a169a.firebaseapp.com',
    storageBucket: 'chat-app-a169a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12AUrzQAu88VNRtF5201FvAnZdyM63bQ',
    appId: '1:423063738443:android:1bfba50f053480f4e995ce',
    messagingSenderId: '423063738443',
    projectId: 'chat-app-a169a',
    storageBucket: 'chat-app-a169a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuIpXbWlv1qgkWMYSCEvDYD4rm9MRv6k',
    appId: '1:423063738443:ios:8030af22edb20dd7e995ce',
    messagingSenderId: '423063738443',
    projectId: 'chat-app-a169a',
    storageBucket: 'chat-app-a169a.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPuIpXbWlv1qgkWMYSCEvDYD4rm9MRv6k',
    appId: '1:423063738443:ios:811ddf4b2bae975be995ce',
    messagingSenderId: '423063738443',
    projectId: 'chat-app-a169a',
    storageBucket: 'chat-app-a169a.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
